config/routes.rb
Rails.application.routes.draw do
  resources :styles

  resources :memberships

  resources :beer_clubs

  resources :users
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only:[:index, :show]

  root 'breweries#index'
  resources :beers
  resources :breweries

  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'places', to: 'places#index'

  delete 'signout', to: 'sessions#destroy'

  post 'places', to:'places#search'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ratebeer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navibar">
    <%= link_to 'Breweries', breweries_path %>
    <%= link_to 'Beers', beers_path %>
    <%= link_to 'Beer styles', styles_path %>
    <%= link_to 'Ratings', ratings_path %>
    <%= link_to 'Users', users_path %>
    <%= link_to 'BeerClubs', beer_clubs_path %>
    <%= link_to 'Search bars', places_path %>
    |
    <% if current_user %>
      <%= link_to current_user.username, current_user %>
      <%= link_to 'Rate a beer', new_rating_path%>
      <%= link_to 'Join a club', new_membership_path%>
      <%= link_to 'Singout', session_path, method: :delete, data: { confirm: 'Are you sure?' } %>
      <%else%>
      <%= link_to 'Signin', signin_path%>
      <%= link_to 'Signup', signup_path%>
    <% end %>
</div>




<%= yield %>

</body>
</html>